### PR TITLE
Handle component creator's result being new'ed from within react 0.14, #123

### LINKED ISSUE #123: Omniscient 4.0 Components Seem to Not Working with React Test Utilities
Hello, it seems that React components created by Omniscient 4.0 do not work well with React 0.14 test utilities. In my tests, TestUtils.renderIntoDocument() runs correctly with components created by React.createClass(). If I input a component created by Omniscient, it always return null.

Please run the following tests for more details. I hope this issue will be resolved soon.

```js
var chai = require('chai'),
    expect = chai.expect,
    omniscient = require('omniscient'),
    React = require('react'),
    TestUtils = require('react-addons-test-utils');

const ReactComponent = React.createClass({
  render() {
    return (
      <div>
        <input type="text" value="Hello from ReactComponent"/>
      </div>
    );
  }
});

const OmniscientComponent = omniscient('OmniscientComponent', function(props) {
  return (
    <div>
      <input type="text" value='OmniscientComponent says "Hello"'/>
    </div>
  );
});

describe('ReactComponent', function() {
  it('renders input field with correct value', function() {
    let reactComp = TestUtils.renderIntoDocument(
      <ReactComponent/>
    );

    let input = TestUtils
      .findRenderedDOMComponentWithTag(reactComp, 'input');

    expect(input).not.to.be.null;
    expect(input.value).to.equal('Hello from ReactComponent');
  });
});

describe('OmniscientComponent', function() {
  it('renders input field with correct value', function() {
    let component = TestUtils.renderIntoDocument(
      <OmniscientComponent/>
    );

    let input = TestUtils
      .findRenderedDOMComponentWithTag(component, 'input');

    expect(input).not.to.be.null;
    expect(input.value).to.equal('OmniscientComponent says "Hello"');
  });
});
```

Thank you and sorry for my bad English.

### PR DESCRIPTION
**Pull request by torgeir**
A change in 0.14 results in our component creator's returned `create` function being new'ed from inside React, due to a naive check for handling stateless react components that are plain functions.

https://github.com/facebook/react/blob/88bae3fb73511893519195e451c56896463f669b/src/renderers/shared/reconciler/ReactCompositeComponent.js#L158

This change will return an instance of the react component instead of an element when a third argument that is not a child is passed to our component creator. 

Resolves #123.

### CODE REVIEW

**Comment by torgeir** [comment]
Care to take a look @mikaelbr? Not really pleased with this change, it's [not very elegant](https://github.com/omniscientjs/omniscient/pull/124/files#diff-2422dd4abef863a7859a280e0c9a15fdR243), but I think it ought to work..

File: component.js [hunk 1]
```diff
@@ -274,7 +286,7 @@ function factory (initialOptions) {
       }
 
       return create;
-    };
+    }
```
Comment (mikaelbr) [inline component.js]: Very nit-picky, but should be a semi-colon to conform to the rest of the code style.

Comment (torgeir) [inline component.js]: Semis are for expressions! This is a declaration https://github.com/omniscientjs/omniscient/blob/4d53f7c2c905e99901c90e82e042d588481d7682/component.js#L175

**Comment by mikaelbr** [comment]
LGTM. I don't think it is too bad. I can't think if a more elegant way to solve this. It's a good patch release to be more explicit and potentially fix usage with contexts and more.

File: component.js (hunk 1 above)
Comment (mikaelbr) [inline component.js]: Ah, sorry, I thought this line was for the create expression.
